### ISSUE TITLE
Задача не соотносится с лекцией /7-module/1-task

### ISSUE THREAD

**Issue by stas-dolgachov** [js-tasks-ru/tasks-jsbasic#35]
Вот такая у нас тема: Занятие 7:  Взаимодействие с сервером 
А задача про дату и время.

**Comment by koalex** [comment]
Задача видимо вообще лишняя т.к. в задачнике вообще нет темы про работу с датой и временем. Думаю надо либо удалить задачу либо добавить тему "Работа с датой и временем" и туда перенести задачу.

**Comment by stas-dolgachov** [comment]
@iliakan @burlakilia что думаете?

**Comment by burlakilia** [comment]
Да пожалуй ее надо убрать. Но надо добавить задачу про промисы

пн, 30 дек. 2019 г. в 13:59, Stanislav <notifications@github.com>:

**Comment by iliakan** [comment]
Может по ошибке не туда попала.

**Comment by stas-dolgachov** [comment]
Я создал пулл реквест с вариантом задачи про промисы. Если есть еще какие-то идеи для задач, пожалуйста, предлагайте :) @koalex @burlakilia @iliakan

**Comment by iliakan** [comment]
@stas-dolgachov это тот, который ты раньше делал, да?

**Comment by stas-dolgachov** [comment]
@iliakan не совсем понял тебя. Это новый, создал его только вчера.
